### ISSUE TITLE
Sternchen-Hack deaktivieren und "Dev-Mode"-Switch einbauen

### ISSUE THREAD

**Issue by Xendiadyon** [1601com/metaMandatory#3]
Es soll nicht möglich sein, dass man die Elemente per Sternchen leer lassen kann.

Daher benötigen wir einen dev-Mode-Schalter (verständlich hinterlegt in den Systemeinstellungen), mit dem man das Pflichtfeld vorübergehend deaktivieren kann.

**Comment by LBeckX** [comment]
Ist implementiert (neueste Version, noch nicht veröffentlicht)
